# Importing Necessary Libraries.

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
Ss = StandardScaler()
label = LabelEncoder()
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn import metrics


import warnings
warnings.filterwarnings('ignore')

# Import Models 

In [2]:
from sklearn.linear_model import Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import AdaBoostRegressor


pipels = make_pipeline(StandardScaler(), Lasso())
DT = DecisionTreeRegressor()
rf = RandomForestRegressor()
xgboost = XGBRegressor()
BC = BaggingRegressor(base_estimator = DT)
ADB = AdaBoostRegressor(base_estimator = DT)

In [3]:
df = pd.read_csv('processed.csv')
df.head()

Id  Dwell_Type Zone_Class LotFrontage  LotArea Road_Type Property_Shape  \
0   1          60         RL        65.0     8450      Pave            Reg   
1   2          20         RL        80.0     9600      Pave            Reg   
2   3          60         RL        68.0    11250      Pave            IR1   
3   4          70         RL        60.0     9550      Pave            IR1   
4   5          60         RL        84.0    14260      Pave            IR1   

  LandContour Utilities LotConfig  ... EnclosedPorch 3SsnPorch ScreenPorch  \
0         Lvl    AllPub    Inside  ...             0         0           0   
1         Lvl    AllPub       FR2  ...             0         0           0   
2         Lvl    AllPub    Inside  ...             0         0           0   
3         Lvl    AllPub    Corner  ...           272         0           0   
4         Lvl    AllPub       FR2  ...             0         0           0   

  PoolArea MiscVal MoSold  YrSold  SaleType  SaleCondition  \
0        0       0      2    2008        WD         Normal   
1        0       0      5    2007        WD         Normal   
2        0       0      9    2008        WD         Normal   
3        0       0      2    2006        WD        Abnorml   
4        0       0     12    2008        WD         Normal   

   Property_Sale_Price  
0               208500  
1               181500  
2               223500  
3               140000  
4               250000  

[5 rows x 76 columns]

In [4]:
df.shape

(2073, 76)

In [5]:
for i in df.columns:
    if (df[i].dtype == 'object'):
        df[i] = label.fit_transform(df[i])

In [6]:
df.head()

Id  Dwell_Type  Zone_Class  LotFrontage  LotArea  Road_Type  \
0   1          60           3           75     8450          1   
1   2          20           3           90     9600          1   
2   3          60           3           78    11250          1   
3   4          70           3           70     9550          1   
4   5          60           3           94    14260          1   

   Property_Shape  LandContour  Utilities  LotConfig  ...  EnclosedPorch  \
0               3            3          0          4  ...              0   
1               3            3          0          2  ...              0   
2               0            3          0          4  ...              0   
3               0            3          0          0  ...            272   
4               0            3          0          2  ...              0   

   3SsnPorch  ScreenPorch  PoolArea  MiscVal  MoSold  YrSold  SaleType  \
0          0            0         0        0       2    2008         8   
1          0            0         0        0       5    2007         8   
2          0            0         0        0       9    2008         8   
3          0            0         0        0       2    2006         8   
4          0            0         0        0      12    2008         8   

   SaleCondition  Property_Sale_Price  
0              4               208500  
1              4               181500  
2              4               223500  
3              0               140000  
4              4               250000  

[5 rows x 76 columns]

In [7]:
X = df.drop(['Id','Property_Sale_Price'], axis = 1)
y = df['Property_Sale_Price']

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state = 50)

# Building Model and appying CrossValidation function simultaneously.

In [21]:
lsscore =cross_val_score(estimator = pipels, X = X_train, y = y_train, cv = 10)
print("%0.2f mean with a standard deviation of %0.2f" % (lsscore.mean(), lsscore.std()))

0.68 mean with a standard deviation of 0.37


In [22]:
lsscore

array([ 0.4690239 , -0.37234594,  0.85801263,  0.87794471,  0.77378873,
        0.86959189,  0.84968042,  0.84596929,  0.88041295,  0.7925423 ])

In [23]:
dtscore =cross_val_score(estimator = DT, X = X_train, y = y_train, cv = 10)
print("%0.2f mean with a standard deviation of %0.2f" % (dtscore.mean(), dtscore.std()))

0.74 mean with a standard deviation of 0.16


In [24]:
dtscore

array([0.67594984, 0.48453966, 0.83938969, 0.80998764, 0.402781  ,
       0.85044507, 0.79289352, 0.90692988, 0.8774131 , 0.77367717])

In [25]:
rfscore =cross_val_score(estimator = rf, X = X_train, y = y_train, cv = 10)
print("%0.2f mean with a standard deviation of %0.2f" % (rfscore.mean(), rfscore.std()))

0.87 mean with a standard deviation of 0.12


In [26]:
rfscore

array([0.9058309 , 0.5281064 , 0.91631936, 0.91957494, 0.89844531,
       0.93001715, 0.90761959, 0.90162743, 0.93689777, 0.86388393])

In [27]:
bcscore =cross_val_score(estimator = BC, X = X_train, y = y_train, cv = 10)
print("%0.2f mean with a standard deviation of %0.2f" % (bcscore.mean(), bcscore.std()))

0.86 mean with a standard deviation of 0.14


In [28]:
bcscore

array([0.8982957 , 0.44541084, 0.9164674 , 0.91092059, 0.89211255,
       0.93951463, 0.89696197, 0.9040344 , 0.91838418, 0.8356633 ])

In [29]:
adbscore =cross_val_score(estimator = ADB, X = X_train, y = y_train, cv = 10)
print("%0.2f mean with a standard deviation of %0.2f" % (adbscore.mean(), adbscore.std()))

0.87 mean with a standard deviation of 0.15


In [30]:
adbscore

array([0.89369239, 0.4188158 , 0.95253742, 0.93370415, 0.90919851,
       0.91903485, 0.90714832, 0.92068584, 0.93703184, 0.88385692])

In [31]:
xgbscore =cross_val_score(estimator = xgboost, X = X_train, y = y_train, cv = 10)
print("%0.2f mean with a standard deviation of %0.2f" % (xgbscore.mean(), xgbscore.std()))

0.86 mean with a standard deviation of 0.15


In [32]:
xgbscore

array([0.85685373, 0.43615111, 0.9231341 , 0.91560872, 0.92134294,
       0.93019246, 0.90420138, 0.92375607, 0.95699458, 0.85462221])

# Now Lets try Fine tuning the models using Grid-Search-CV

In [36]:
rf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}